### ISSUE TITLE
new line char in answer

### ISSUE THREAD

**Issue by ecevinoth** [leej11/anki-templates#1]
how to add new line char in answer field?

i would like to type new line char as part of answer section, when i press enter key inside type box it showing actual answer instead of adding additional new line char in answer type box.

**Comment by leej11** [comment]
Hi @ecevinoth, I've got a blog post about how you can do this. Check it out [here](https://www.liamgower.com/main-blog/multi-line-typed-answers-in-anki).

**Comment by leej11** [comment]
@ecevinoth I've also just PR'd in a new folder that has the template files for you. 👍  Let me know if you have any further questions, happy to help.
